### ISSUE TITLE
Add link to syntax guide to edit dialogue tip on error.

### ISSUE THREAD

**Issue by dceejay** [Lighthouse-Automation/node-red-contrib-later#4]
Hi,

any chance you can add a link to the later syntax docs. For those times I get the syntax wrong and it pops up an error. As the dialogue is modal the link to the docs in the info panel is no longer accessible... so it would be nice to have a link directly below the error. EG change line 112 to be

```
    <span id="error-bad" style="color:red">bad</span></p>
    <p>See the <i><a href="http://bunkat.github.io/later/parsers.html#text" target="_new">syntax guide</a></i> for more details.</p>
```

Many thanks

**Comment by d-o** [comment]
Good suggestion, Thanks Dave.
